from .adversarial_loss import GenAdversarialLoss, DiscAdversarialLoss
from .final_loss import FinalLoss
from .identity_preservation_loss import IdentityPreservationLoss
from .landmark_alignment_loss import LandmarkAlignmentLoss
from .reconstruction_loss import ReconstructionLoss
from .style_transfer_loss import StyleTransferLoss
