defaults:
  - dataset: celebahq
  - models: models
  - losses/generator_losses
  - losses/discriminator_losses
  - optimizers: adam
  
exp_name: test_2103

batch_size: 4
num_workers: 4
num_epochs: 10
use_wandb: False

generator_loss:
  _target_: faceswap.losses.FinalLoss
  losses:
    - ${losses.GenAdversarialLoss}
    - ${losses.ReconstructionLoss}
    - ${losses.IdentityPreservationLoss}
  coefs:
    - 1
    - 10
    - 1

discriminator_loss:
  _target_: faceswap.losses.FinalLoss
  losses:
    - ${losses.DiscAdversarialLoss}
  coefs:
    - 1

scheduler: False
scheduler_step: 5000
scheduler_gamma: 0.2


loss_log_step: 10
wandb_img_step: 100

model_save_step: 5000
model_save_dir: exp_results/

image_size: 1024
latent: 512
n_mlp: 8
channel_multiplier: 2
coarse: 7
least_size: 8
largest_size: 512
mapping_layers: 18
mapping_fmaps: 512
mapping_lrmul: 1
mapping_nonlinearity: 'linear'
