GenAdversarialLoss:
  _target_: faceswap.losses.GenAdversarialLoss

IdentityPreservationLoss:
  _target_: faceswap.losses.IdentityPreservationLoss
  path_to_model: ./pretrained/WFLW_4HG.pth

LandmarkAlignmentLoss:
  _target_: faceswap.losses.LandmarkAlignmentLoss

ReconstructionLoss:
  _target_: faceswap.losses.ReconstructionLoss
  alpha: 0.8
