GenAdversarialLoss:
  _target_: faceswap.losses.GenAdversarialLoss

IdentityPreservationLoss:
  _target_: faceswap.losses.IdentityPreservationLoss

LandmarkAlignmentLoss:
  _target_: faceswap.losses.LandmarkAlignmentLoss
  path_to_model: ./pretrained/WFLW_4HG.pth

ReconstructionLoss:
  _target_: faceswap.losses.ReconstructionLoss
  alpha: 0.8

StyleTransferLoss:
  _target_: faceswap.losses.StyleTransferLoss
